config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#hello"
  resources :todos
end

app/models/Todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello
    render plain: "hello pages"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo,only:[:edit,:update,:destroy,:show]
  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:notice] = "Data save into database"
      redirect_to todo_path(@todo)
    else
      render "new"
    end
  end
  def index
    @todos = Todo.all
  end
  def show
  end

  def edit
  end

  def destroy
    @todo.destroy
    flash[:notice] = "Todos deleted successfully"
    redirect_to todos_path(@todos)
  end
  def update
    if @todo.update(todo_params)
      flash[:notice] = "Todos update successfully"
      redirect_to todo_path(@todo)
    else
      render "edit"
    end
  end
  private
  def set_todo
    @todo = Todo.find(params[:id])
  end
  def todo_params
    params.require(:todo).permit(:name,:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |name,msg| %>
    <%= msg %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/hello.html.erb
<h1>hello world</h1>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <h2>The following errors prevented the todo from being saved</h2>
  <ul>
    <% @todo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @todo do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit Todos</h1>
<%= render "form" %>

app/views/todos/index.html.erb
<h1>Listing all Todos</h1>
<p>
  <%= link_to "Create a Todo", new_todo_path %>
</p>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <% @todos.each do |todo| %>
  <tr>
    <td><%= todo.name %></td>
    <td><%= todo.description %></td>
    <td><%= link_to "Edit todo", edit_todo_path(todo) %>
    <td><%= link_to "Show todo", todo_path(todo) %>
    <td><%= link_to "Delete", todo_path(todo), method: :delete, data: {confirm: "Are u sure"}%>
    </td>
  </tr>

<% end %>
</table>

app/views/todos/new.html.erb
<h1>Create new todos</h1>
<%= render "form" %>

app/views/todos/show.html.erb
<h1>Show Todos</h1>
<%= @todo.name %>
<%= @todo.description %>
<%= link_to "listing all todos", todos_path %>
<%= link_to "edit todos", edit_todo_path(@todo) %>